apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
  labels:
    app: conversao-temperatura
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: conversao-temperatura
          image: fabricioveronez/conversao-temperatura:v1
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura-service
  labels:
    app: conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
