global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']  
  - job_name: 'conversao-temperatura'
    static_configs:
      - targets: ['conversao-temperatura:8080']
        labels:
          service: 'conversao'
    scrape_interval: 5s
    scrape_timeout: 2s
    metrics_path: '/metrics'